name: CMake

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install MSBuild with C++ support
      run: |
        choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended --includeOptional --quiet --wait"
      
    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11

    - name: Configure CMake
      run: cmake -B build

    - name: Build
      run: cmake --build build
