name: configure CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [win64]

    steps:
    - uses: actions/checkout@v4
    - name: Dependencies
      run: sudo apt update && sudo apt-get install -y autoconf automake autotools-dev libsdl2-dev libtool pkg-config libpng-dev
    - name: generate configure script
      run: ./autogen.sh
    - name: configure
      run:  ./configure --with-tests
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: qrencode-build
        path: |
          ./*.c
          ./*.o
          ./*.a
          ./*.so
          ./src/qrencode
